### ISSUE TITLE
Plugin not available in ionic-native

### ISSUE THREAD

**Issue by rupalpatel0008** [sebastianbaar/cordova-plugin-nativegeocoder#1]
I have tried this plugin in my demo app. Its giving me following error on build.

<myprojectdir>/node_modules/ionic-native/dist/es5/index"' has no exported member 'NativeGeocoder', 'NativeGeocoderReverseResult', 'NativeGeocoderForwardResult'.

**ionic-native version: 2.2.11**

**Comment by RafilAlArs** [comment]
+1 Same happened for me yesterday.

**Comment by sebastianbaar** [comment]
Hey guys, thank you for pointing that out. I will have a look at it and let you know how to fix this!

**Comment by sebastianbaar** [comment]
@rupalpatel0008 @RafilAlArs 
Hey, I cannot repreduce your problem. I uploaded a [demo](https://github.com/sebastianbaar/cordova-plugin-nativegeocoder/tree/master/demo) project - you should check it out and give me some feedback
Cheers

Edit: You have have to use ionic-native >= v2.4.1.
