### ISSUE TITLE
Hangs on build

### ISSUE THREAD

**Issue by ustincameron** [sebastianbaar/cordova-plugin-nativegeocoder#10]
I've been building an Ionic/Cordova app with a lot of success but now that I've added this plugin everytime I run "Cordova run ios" it now takes 5 minutes instead of 15 seconds to build the app. 

It seems to hang at the line "NativeGeocoder.o".

What is it doing that whole time? Feels like it's downloading something heavy... How do I resolve this as it's now becoming a massive time constraint while working on other features. Plus to make matters worse the device times out and locks so half the time I have to re-run the 5 minute build simply based on a permission issue.

Sorry for such a "petty" issue but I've googled to no avail.  No other package has caused this issue.

**Comment by sebastianbaar** [comment]
Hey socca1157, I cannot reproduce that error. Do you have some example code/repo that shows this error?

**Comment by MichaelMassalas** [comment]
Hi Sebastian,

I have been experiencing the same issue, as well. I do not use Ionic. Whenever I try to compile for iOS device or emulator, it takes 5 minutes to complete. Here is where it hangs:
`CompileSwift normal arm64 /Users/user/Desktop/MobileProjects/fareway/platforms/ios/Fareway/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift
    cd /Users/user/Desktop/MobileProjects/fareway/platforms/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c -primary-file /Users/user/Desktop/MobileProjects/fareway/platforms/ios/Fareway/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift -target arm64-apple-ios9.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk -I /Users/user/Desktop/MobileProjects/fareway/platforms/ios/build/device -F /Users/user/Desktop/MobileProjects/fareway/platforms/ios/build/device -g -module-cache-path /Users/user/Library/Developer/Xcode/DerivedData/ModuleCache -serialize-debugging-options -Xcc -I/Users/user/Library/Developer/Xcode/DerivedData/Fareway-fjnmiunlqiiqrafjbtceyuttpxqf/Build/Intermediates/ArchiveIntermediates/Fareway/IntermediateBuildFilesPath/Fareway.build/Debug-iphoneos/Fareway.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/user/Library/Developer/Xcode/DerivedData/Fareway-fjnmiunlqiiqrafjbtceyuttpxqf/Build/Intermediates/ArchiveIntermediates/Fareway/IntermediateBuildFilesPath/Fareway.build/Debug-iphoneos/Fareway.build/Fareway-generated-files.hmap -Xcc -I/Users/user/Library/Developer/Xcode/DerivedData/Fareway-fjnmiunlqiiqrafjbtceyuttpxqf/Build/Intermediates/ArchiveIntermediates/Fareway/IntermediateBuildFilesPath/Fareway.build/Debug-iphoneos/Fareway.build/Fareway-own-target-headers.hmap -Xcc -I/Users/user/Library/Developer/Xcode/DerivedData/Fareway-fjnmiunlqiiqrafjbtceyuttpxqf/Build/Intermediates/ArchiveIntermediates/Fareway/IntermediateBuildFilesPath/Fareway.build/Debug-iphoneos/Fareway.build/Fareway-all-target-headers.hmap -Xcc -iquote -Xcc /Users/user/Library/Developer/Xcode/DerivedData/Fareway-fjnmiunlqiiqrafjbtceyuttpxqf/Build/Intermediates/ArchiveIntermediates/Fareway/IntermediateBuildFilesPath/Fareway.build/Debug-iphoneos/Fareway.build/Fareway-project-headers.hmap -Xcc -I/Users/user/Desktop/MobileProjects/fareway/platforms/ios/build/device/include -Xcc -I/Users/user/Library/Developer/Xcode/DerivedData/Fareway-fjnmiunlqiiqrafjbtceyuttpxqf/Build/Intermediates/ArchiveIntermediates/Fareway/InstallationBuildProductsLocation/Applications/usr/local/lib/include -Xcc -I/Users/user/Library/Developer/Xcode/DerivedData/Fareway-fjnmiunlqiiqrafjbtceyuttpxqf/Build/Intermediates/ArchiveIntermediates/Fareway/IntermediateBuildFilesPath/UninstalledProducts/include -Xcc -I/Users/user/Library/Developer/Xcode/DerivedData/Fareway-fjnmiunlqiiqrafjbtceyuttpxqf/Build/Intermediates/ArchiveIntermediates/Fareway/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/include -Xcc -I/Users/user/Desktop/MobileProjects/fareway/platforms/ios/build/device -Xcc -I/Users/user/Library/Developer/Xcode/DerivedData/Fareway-fjnmiunlqiiqrafjbtceyuttpxqf/Build/Intermediates/ArchiveIntermediates/Fareway/IntermediateBuildFilesPath/Fareway.build/Debug-iphoneos/Fareway.build/DerivedSources/arm64 -Xcc -I/Users/user/Library/Developer/Xcode/DerivedData/Fareway-fjnmiunlqiiqrafjbtceyuttpxqf/Build/Intermediates/ArchiveIntermediates/Fareway/IntermediateBuildFilesPath/Fareway.build/Debug-iphoneos/Fareway.build/DerivedSources -Xcc -DDEBUG=1 -Xcc -working-directory/Users/user/Desktop/MobileProjects/fareway/platforms/ios -emit-module-doc-path /Users/user/Library/Developer/Xcode/DerivedData/Fareway-fjnmiunlqiiqrafjbtceyuttpxqf/Build/Intermediates/ArchiveIntermediates/Fareway/IntermediateBuildFilesPath/Fareway.build/Debug-iphoneos/Fareway.build/Objects-normal/arm64/NativeGeocoder~partial.swiftdoc -serialize-diagnostics-path /Users/user/Library/Developer/Xcode/DerivedData/Fareway-fjnmiunlqiiqrafjbtceyuttpxqf/Build/Intermediates/ArchiveIntermediates/Fareway/IntermediateBuildFilesPath/Fareway.build/Debug-iphoneos/Fareway.build/Objects-normal/arm64/NativeGeocoder.dia -import-objc-header /Users/user/Desktop/MobileProjects/fareway/platforms/ios/Fareway/Bridging-Header.h -Onone -parse-as-library -module-name Fareway -emit-module-path /Users/user/Library/Developer/Xcode/DerivedData/Fareway-fjnmiunlqiiqrafjbtceyuttpxqf/Build/Intermediates/ArchiveIntermediates/Fareway/IntermediateBuildFilesPath/Fareway.build/Debug-iphoneos/Fareway.build/Objects-normal/arm64/NativeGeocoder~partial.swiftmodule -emit-dependencies-path /Users/user/Library/Developer/Xcode/DerivedData/Fareway-fjnmiunlqiiqrafjbtceyuttpxqf/Build/Intermediates/ArchiveIntermediates/Fareway/IntermediateBuildFilesPath/Fareway.build/Debug-iphoneos/Fareway.build/Objects-normal/arm64/NativeGeocoder.d -emit-reference-dependencies-path /Users/user/Library/Developer/Xcode/DerivedData/Fareway-fjnmiunlqiiqrafjbtceyuttpxqf/Build/Intermediates/ArchiveIntermediates/Fareway/IntermediateBuildFilesPath/Fareway.build/Debug-iphoneos/Fareway.build/Objects-normal/arm64/NativeGeocoder.swiftdeps -o /Users/user/Library/Developer/Xcode/DerivedData/Fareway-fjnmiunlqiiqrafjbtceyuttpxqf/Build/Intermediates/ArchiveIntermediates/Fareway/IntermediateBuildFilesPath/Fareway.build/Debug-iphoneos/Fareway.build/Objects-normal/arm64/NativeGeocoder.o`

**Comment by MichaelMassalas** [comment]
Hi Sebastian,

I have been experiencing the same issue, as well. I do not use Ionic. Whenever I try to compile for iOS device or emulator, it takes 5 minutes to complete. Here is where it hangs:

CompileSwift normal arm64 /Users/USER/Desktop/MobileProjects/PROJECTNAME/platforms/ios/PROJECTNAME/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift
cd /Users/USER/Desktop/MobileProjects/PROJECTNAME/platforms/ios
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c -primary-file
...
...
...
/Users/USER/Library/Developer/Xcode/DerivedData/PROJECTNAME-fjnmiunlqiiqadsdasdeyuttpxqf/Build/Intermediates/ArchiveIntermediates/PROJECTNAME/IntermediateBuildFilesPath/PROJECTNAME.build/Debug-iphoneos/PROJECTNAME.build/Objects-normal/arm64/NativeGeocoder.o

**Comment by steveacalabro** [comment]
+1 using Ionic@latest build takes around 5 mins as well and hangs on the same line

**Comment by sebastianbaar** [comment]
Hey guys, it was a problem with the Swift compiler. Please update the plugin.
Cheers
