### ISSUE TITLE
Error: [$injector:unpr] Unknown provider: NativeGeocoderProvider 

### ISSUE THREAD

**Issue by jatinbphp** [sebastianbaar/cordova-plugin-nativegeocoder#12]
Hello, i install this package, when i am going to use it, it gives me "Error: [$injector:unpr] Unknown provider: NativeGeocoderProvider " error.

Below is my code .
    function Search1Controller($log, header, DialogService, $auth, $localStorage, $state, $rootScope, $scope, API, mapbox, geo, $document, $interval, $timeout, broadcast, toast, $cordovaGeolocation, NativeGeocoder) {

and..
.reverseGeocode(success, failure, 52.5072095, 13.1452818);

        function success(result) {
            alert("The address is: \n\n" + JSON.stringify(result));
        }

        function failure(err) {
            alert(JSON.stringify(err));
        }

**Comment by sebastianbaar** [comment]
It seems like you're using Ionic 1. Please note that this plugin is not available for ngCordova and you cannot import it like other ngCordova plugins. Use native JS instead.
