### ISSUE TITLE
return multiple locations?

### ISSUE THREAD

**Issue by deckikwok** [sebastianbaar/cordova-plugin-nativegeocoder#17]
Is it possible to return the list of locations instead of just one?
e.g. I reckon typing in something ambiguous like 'depot' would yield many possible results? since Android geocoder api states that they return a list.

thanks!

**Comment by sebastianbaar** [comment]
Hey @deckikwok,
thanks for your request. You are right, both Android and iOS return a list of results. My intention for this plugin was to make it as easy as possible. Therefore I decided to just return the first (best) result for forward/reverse geocoding. But I see the advantage of returning multiple result sets... Mh, so what do you think. Should we alter the API and return a list of results by default for both forward and reverse geocoding. Or should we keep the API as is and add additional functions for forward/reverse geocoding with multiple results? Something like 
`nativegeocoder.forwardGeocodeWithResultSet(successCallback, errorCallback, addressString);
 ` 
and 
`nativegeocoder.reverseGeocodeWithResultSet(successCallback, errorCallback, latitude, longitude);`?

What are your thoughts about this?

And most important question: Would you like to help me (PR) with the Android part? ;-)

Cheers!
