### ISSUE TITLE
iOS build error

### ISSUE THREAD

**Issue by axesve** [sebastianbaar/cordova-plugin-nativegeocoder#23]
Hey, I'am trying to build to iOS but Im getting these errors.

Using Swift 1.7.1.

```
`Users/Me/app-ios/platforms/ios/appName/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:5:48: warning: extraneous '_' in parameter: 'command' has no keyword argument name
    @objc(reverseGeocode:) func reverseGeocode(_ command: CDVInvokedUrlCommand) {
                                               ^~
                                               
/Users/Me/app-ios/platforms/ios/appName/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:80:45: warning: extraneous '_' in parameter: 'command' has no keyword argument name
  @objc(forwardGeocode:)func forwardGeocode(_ command: CDVInvokedUrlCommand) {
                                            ^~
                                            
/Users/Me/app-ios/platforms/ios/appName/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:24:52: error: value of type 'CLPlacemark' has no member 'isoCountryCode'
                        resultObj["countryCode"] = placemark.isoCountryCode ?? ""
                                                   ^~~~~~~~~ ~~~~~~~~~~~~~~
/Users/Me/app-ios/platforms/ios/appName/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:34:55: error: incorrect argument label in call (have 'status:messageAs:', expected 'status:messageAsDictionary:')
                        pluginResult = CDVPluginResult(
                                                      ^
/Users/Me/app-ios/platforms/ios/appName/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:42:55: error: incorrect argument label in call (have 'status:messageAs:', expected 'status:messageAsString:')
                        pluginResult = CDVPluginResult(
                                                      ^
/Users/Me/app-ios/platforms/ios/appName/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:51:51: error: incorrect argument label in call (have 'status:messageAs:', expected 'status:messageAsString:')
                    pluginResult = CDVPluginResult(
                                                  ^
/Users/Me/app-ios/platforms/ios/appName/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:58:37: error: value of type 'CDVCommandDelegate' has no member 'send'
                self.commandDelegate!.send(
                ~~~~~~~~~~~~~~~~~~~~^ ~~~~
/Users/Me/app-ios/platforms/ios/appName/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:67:43: error: incorrect argument label in call (have 'status:messageAs:', expected 'status:messageAsString:')
            pluginResult = CDVPluginResult(
                                          ^
/Users/Me/app-ios/platforms/ios/appName/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:72:33: error: value of type 'CDVCommandDelegate' has no member 'send'
            self.commandDelegate!.send(
            ~~~~~~~~~~~~~~~~~~~~^ ~~~~
/Users/Me/app-ios/platforms/ios/appName/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:101:55: error: incorrect argument label in call (have 'status:messageAs:', expected 'status:messageAsDictionary:')
                        pluginResult = CDVPluginResult(
                                                      ^
/Users/Me/app-ios/platforms/ios/appName/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:108:55: error: incorrect argument label in call (have 'status:messageAs:', expected 'status:messageAsString:')
                        pluginResult = CDVPluginResult(
                                                      ^
/Users/Me/app-ios/platforms/ios/appName/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:117:51: error: incorrect argument label in call (have 'status:messageAs:', expected 'status:messageAsString:')
                    pluginResult = CDVPluginResult(
                                                  ^
/Users/Me/app-ios/platforms/ios/appName/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:126:47: error: incorrect argument label in call (have 'status:messageAs:', expected 'status:messageAsString:')
                pluginResult = CDVPluginResult(
                                              ^
/Users/Me/app-ios/platforms/ios/appName/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:133:33: error: value of type 'CDVCommandDelegate' has no member 'send'
            self.commandDelegate!.send(
            ~~~~~~~~~~~~~~~~~~~~^ ~~~~
/Users/Me/app-ios/platforms/ios/appName/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:143:39: error: incorrect argument label in call (have 'status:messageAs:', expected 'status:messageAsString:')
        pluginResult = CDVPluginResult(
                                      ^
/Users/Me/app-ios/platforms/ios/appName/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:148:29: error: value of type 'CDVCommandDelegate' has no member 'send'
        self.commandDelegate!.send(
        ~~~~~~~~~~~~~~~~~~~~^ ~~~~

** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64 /Users/Me/app-ios/platforms/ios/appName/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/Me/app-ios/platforms/ios/cordova/build-debug.xcconfig,-workspace,appName.xcworkspace,-scheme,appName,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone 6s Plus,build,CONFIGURATION_BUILD_DIR=/Users/Me/app-ios/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/Me/app-ios/platforms/ios/build/sharedpch

[ERROR] An error occurred while running cordova build ios (exit code 1).`
```

Im guessing it has something to do with swift, however I do not know how to fix this so I might aswell just post it here...

**Comment by sebastianbaar** [comment]
Hey @axesve, what version of Xcode are you using? Should be 9.x with Swift 4.
Cheers

**Comment by axesve** [comment]
@sebastianbaar Alrighty, I did not know xcode version had any effect on ionic build, most likely I have not updated xCode to 9.x... Thank you!

**Comment by sebastianbaar** [comment]
Ok, try it out and let me know if it helps :-) I'm closing this issue but if you still have some problem just get in touch! Cheers & good luck

**Comment by moezzineb** [comment]
Hello @sebastianbaar, we are in 2020 now and same issue i'm using "@ionic-native/native-geocoder": "^5.26.0" and i have same error as @axesve had but i'm using 👍 
- Xcode 11.6
- Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)

> /Users/marwan/Desktop/BeautyBelle/platforms/ios/Salon SBS/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:28:46: error: use of undeclared type 'CDVPlugin'
@objc(NativeGeocoder) class NativeGeocoder : CDVPlugin {
                                             ^~~~~~~~~
/Users/marwan/Desktop/BeautyBelle/platforms/ios/Salon SBS/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:34:59: error: use of undeclared type 'CDVInvokedUrlCommand'
    @objc(reverseGeocode:) func reverseGeocode(_ command: CDVInvokedUrlCommand) {
                                                          ^~~~~~~~~~~~~~~~~~~~
/Users/marwan/Desktop/BeautyBelle/platforms/ios/Salon SBS/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:150:58: error: use of undeclared type 'CDVInvokedUrlCommand'
    @objc(forwardGeocode:)func forwardGeocode(_ command: CDVInvokedUrlCommand) {
                                                         ^~~~~~~~~~~~~~~~~~~~
/Users/marwan/Desktop/BeautyBelle/platforms/ios/Salon SBS/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:28:2: error: only classes that inherit from NSObject can be declared @objc
@objc(NativeGeocoder) class NativeGeocoder : CDVPlugin {
~^~~~~~~~~~~~~~~~~~~~~
/Users/marwan/Desktop/BeautyBelle/platforms/ios/Salon SBS/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:35:28: error: use of unresolved identifier 'CDVPluginResult'
        var pluginResult = CDVPluginResult(status: CDVCommandStatus_ERROR)
                           ^~~~~~~~~~~~~~~
/Users/marwan/Desktop/BeautyBelle/platforms/ios/Salon SBS/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:35:52: error: use of unresolved identifier 'CDVCommandStatus_ERROR'
        var pluginResult = CDVPluginResult(status: CDVCommandStatus_ERROR)
                                                   ^~~~~~~~~~~~~~~~~~~~~~
/Users/marwan/Desktop/BeautyBelle/platforms/ios/Salon SBS/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:41:32: error: use of unresolved identifier 'CDVPluginResult'
                pluginResult = CDVPluginResult(status: CDVCommandStatus_ERROR, messageAs: "Geocoder is busy. Please try again later.")
                               ^~~~~~~~~~~~~~~
/Users/marwan/Desktop/BeautyBelle/platforms/ios/Salon SBS/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:41:56: error: use of unresolved identifier 'CDVCommandStatus_ERROR'
                pluginResult = CDVPluginResult(status: CDVCommandStatus_ERROR, messageAs: "Geocoder is busy. Please try again later.")
                                                       ^~~~~~~~~~~~~~~~~~~~~~
/Users/marwan/Desktop/BeautyBelle/platforms/ios/Salon SBS/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:73:28: error: use of unresolved identifier 'CDVPluginResult'
            pluginResult = CDVPluginResult(status: CDVCommandStatus_ERROR, messageAs: "Expected two non-empty double arguments.")
                           ^~~~~~~~~~~~~~~
/Users/marwan/Desktop/BeautyBelle/platforms/ios/Salon SBS/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:73:52: error: use of unresolved identifier 'CDVCommandStatus_ERROR'
            pluginResult = CDVPluginResult(status: CDVCommandStatus_ERROR, messageAs: "Expected two non-empty double arguments.")
                                                   ^~~~~~~~~~~~~~~~~~~~~~
/Users/marwan/Desktop/BeautyBelle/platforms/ios/Salon SBS/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:151:28: error: use of unresolved identifier 'CDVPluginResult'
        var pluginResult = CDVPluginResult(status: CDVCommandStatus_ERROR)
                           ^~~~~~~~~~~~~~~
/Users/marwan/Desktop/BeautyBelle/platforms/ios/Salon SBS/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:151:52: error: use of unresolved identifier 'CDVCommandStatus_ERROR'
        var pluginResult = CDVPluginResult(status: CDVCommandStatus_ERROR)
                                                   ^~~~~~~~~~~~~~~~~~~~~~
/Users/marwan/Desktop/BeautyBelle/platforms/ios/Salon SBS/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:156:32: error: use of unresolved identifier 'CDVPluginResult'
                pluginResult = CDVPluginResult(status: CDVCommandStatus_ERROR, messageAs: "Geocoder is busy. Please try again later.")
                               ^~~~~~~~~~~~~~~
/Users/marwan/Desktop/BeautyBelle/platforms/ios/Salon SBS/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:156:56: error: use of unresolved identifier 'CDVCommandStatus_ERROR'
                pluginResult = CDVPluginResult(status: CDVCommandStatus_ERROR, messageAs: "Geocoder is busy. Please try again later.")
                                                       ^~~~~~~~~~~~~~~~~~~~~~
/Users/marwan/Desktop/BeautyBelle/platforms/ios/Salon SBS/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:187:28: error: use of unresolved identifier 'CDVPluginResult'
            pluginResult = CDVPluginResult(status: CDVCommandStatus_ERROR, messageAs: "Expected a non-empty string argument.")
                           ^~~~~~~~~~~~~~~
/Users/marwan/Desktop/BeautyBelle/platforms/ios/Salon SBS/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:187:52: error: use of unresolved identifier 'CDVCommandStatus_ERROR'
            pluginResult = CDVPluginResult(status: CDVCommandStatus_ERROR, messageAs: "Expected a non-empty string argument.")
                                                   ^~~~~~~~~~~~~~~~~~~~~~

** BUILD FAILED **


The following build commands failed:
        CompileSwift normal x86_64 /Users/marwan/Desktop/BeautyBelle/platforms/ios/Salon\ SBS/Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
xcodebuild: Command failed with exit code 65
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build ios --release exited with exit code 65.
        
        Re-running this command with the --verbose flag may provide more information.

Please help me with already two days without any solution. 
Cheers.

**Comment by gklasen** [comment]
Are there any news?

**Comment by ChaitGSZyx** [comment]
HI any update on this?
