### ISSUE TITLE
Cordova 8 and add-swift-support

### ISSUE THREAD

**Issue by t91710** [sebastianbaar/cordova-plugin-nativegeocoder#24]
Hello,
It is not possible to install the plugin if you use cordova 8 (on a Mac at least). This is because of the 

`<dependency id="cordova-plugin-add-swift-support" version="1.7.0"/>`

in the file plugin.xml, row 45. The add-swift-support plugin has a bug in version 1.7.0 which is resolved in 1.7.1. Is it possible to change the dependency?

The changes can be checked here: https://github.com/akofman/cordova-plugin-add-swift-support/releases/tag/1.7.1

**Comment by sebastianbaar** [comment]
@t91710 thanks for pointing that out! Updated the dependency 'cordova-plugin-add-swift-support' to 1.7.1
Cheers
