### ISSUE TITLE
Let the user select locale

### ISSUE THREAD

**Issue by khoshrou** [sebastianbaar/cordova-plugin-nativegeocoder#26]
Hi
I really loved this plugin. Thanks for great job.
It would be very helpful if you let the use select locale. I mean in addition to useLocale add an option parameter which is a string and accepts locales like "en-US" or "fa-IR", ...
Thanks

**Comment by sebastianbaar** [comment]
Hi @khoshrou thank you very much! If I find the time I will have a look at it. I think it would be a useful extension.
Cheers

**Comment by khoshrou** [comment]
Great

**Comment by sebastianbaar** [comment]
Added 👍 
Please test with the new release v3.1.0. As soon as you set the defaultLocale e.g. 'fa-IR' the results will be returned in that locale (only works for Android and iOS 11+)

I would love to get some feedback on that :-)

Cheers!
