### ISSUE TITLE
Ionic Native Geocoder “Cannot find a location.”

### ISSUE THREAD

**Issue by binDebug** [sebastianbaar/cordova-plugin-nativegeocoder#27]
While searching for coordinates, i.e. forwardGeocoding, the plugin is returning "Cannot find a location." 

This is the method in my provider -
`//This calls the Native geocoder and returns the geocoordinates. 
  getGeoCode(address: string): Promise<any> {
    console.log('The address key is - ' + address);
    return new Promise((resolve, reject) => {
      this.nativeGeocoder.forwardGeocode(address)
        .then((nativegeocoordinates: NativeGeocoderForwardResult) => {
          console.log('The coordinates are - ' + JSON.stringify(nativegeocoordinates));
          let addressCoordinates: DeliveryAddressCoordinates = nativegeocoordinates;
          resolve(addressCoordinates);
        })
        .catch((error: any) => {
          console.log(JSON.stringify(error));
          reject(error);
        });
    })
  }`

The method accepts an address string as input. So I get the address from google places API, and pass the description here.

Now, for certain addresses, it just doesn't seem to find the coordinates, and returns a "Cannot find a location" message. For e.g. "**_Bhadra Brookefields Apartment B Block, Kundanahalli Lake Road, Kundalahalli, Brookefield, Bengaluru, Karnataka, India_**" is a valid address and returns the coordinates, while "**_Times Square 42 Street Station, New York, NY, USA_**" does not find a match and returns a message saying - "Cannot find a location".

The "Cannot find a location" seems to be originating from the [code here on line #182](https://github.com/sebastianbaar/cordova-plugin-nativegeocoder/blob/master/src/android/NativeGeocoder.java), where it is referencing the Android class.

Is this a known issue? Or is there something that I am doing wrong?

**Comment by sebastianbaar** [comment]
Hey @binDebug,
which version of cordova-plugin-nativegeocoder are you using? I have tested with the latest version v3.1.1 and it works both on Android and iOS (for "Times Square 42 Street Station, New York, NY, USA" I get lat: 40.755... lon: -73.987...).

Please update the plugin to the latest version and try again. If you still have this error please give more info about the OS, OS version, device, plugin version.

Cheers

**Comment by binDebug** [comment]
Thank you Sebastian, firstly for this library, and second for the response. 

The version seems to be just the one you mention. Please find below a snip of my package.json 
![image](https://user-images.githubusercontent.com/17793833/37586319-ff825866-2b81-11e8-9894-60214ada4748.png)

**Comment by sebastianbaar** [comment]
Ok, first please uninstall/reinstall the plugin and try again:
`ionic cordova plugin remove cordova-plugin-nativegeocoder`
`ionic cordova plugin add cordova-plugin-nativegeocoder`

If you still got an error please give more infos about your setting: is it on iOS **AND** Android?, on which device are you testing? (notice that the plugin won't work on Android emulator)

**Comment by binDebug** [comment]
Ah! therein lies the catch, you mention emulator and that is where I am testing. Thanks for that. I shall test on another device and let you know. 

Just curious, why wouldn't it work on an emulator? Also, why would it work with specific addresses while not working with others?

Cheers!

**Comment by sebastianbaar** [comment]
I'm not quite sure why it does not work. It's somehow related to Google Play Services not working on an emulator but that's required for Geocoder to work. According to the [docs](https://developer.android.com/reference/android/location/Geocoder.html):
> The Geocoder class requires a backend service that is not included in the core android framework. The Geocoder query methods will return an empty list if there no backend service in the platform.

Please test on a real device and give some feedback so I know if I can close this issue.

Cheers!
