### ISSUE TITLE
Xcode9 dont support swift 2.x

### ISSUE THREAD

**Issue by Story5** [sebastianbaar/cordova-plugin-nativegeocoder#29]

**Comment by sebastianbaar** [comment]
Correct. 

This plugin supports Swift 4.1. If you have any issue with your Swift version, please file an issue at the cordova-plugin-add-swift-support repo: https://github.com/akofman/cordova-plugin-add-swift-support

Cheers

**Comment by Story5** [comment]
@sebastianbaar  Thank your attention.
I fixed it by add the `<preference name="UseSwiftLanguageVersion" value="4" />` within the `<platform name="ios">`inside my project's `config.xml`

**Comment by sebastianbaar** [comment]
Glad to hear :-)
