### ISSUE TITLE
this.nativeGeocoder.reverseGeocode return error -- > "CLGeocoder:reverseGeocodeLocation Error" on ios12 platform

### ISSUE THREAD

**Issue by einzweindrey** [sebastianbaar/cordova-plugin-nativegeocoder#33]
Hi guys! 
I get an error when trying to geocoding the coordinates on iOS1.  Before updating the OS, everything was ok. Android also works without problems. Perhaps you can tell the reason?

`this.nativeGeocoder.reverseGeocode(coordinates.lat, coordinates.long, options)
            .then((result: NativeGeocoderReverseResult[]) => {
                 console.log(result[0]);
            })
            .catch((error: any) => {
                console.log('reverseGeocodeErr', error);
            });`

**Comment by sebastianbaar** [comment]
Hey @einzweindrey, could you please post the error.

**Comment by einzweindrey** [comment]
Hi @sebastianbaar! In some magical way, everything works again. Holy weekend! )) The text of the error was - "CLGeocoder: reverseGeocodeLocation Error". Now everything works as usual. I do not know what happened. Perhaps google services ... I think the issue can be closed. Thanks for being ready to help me solve the problem!

**Comment by sebastianbaar** [comment]
Hey @einzweindrey, that's great to hear ;-) I'll close the issue for now. 
Cheers
