### ISSUE TITLE
Forward geocoding to return location name and type

### ISSUE THREAD

**Issue by tijuhasz** [sebastianbaar/cordova-plugin-nativegeocoder#35]
The forward geocoding function returns an array of latitude, longitude values. This is not enough for my application, because the user reasonably needs the names of the locations returned to choose from. The formatted_address value of the geocoding service is good to have because the user may not type in a full address (ex. 'Philadelph', so the app cannot rely on the user input later on to identify/label this location. The type of the location returned is also interesting and would be nice to have it. 

In the google geocoding service, the values requested here are:
 types[]: string,
 formatted_address: string,

See also:
https://developers.google.com/maps/documentation/javascript/geocoding#GeocodingAddressTypes
https://developers.google.com/maps/documentation/geocoding/intro

Thank you for the great package!

**Comment by tijuhasz** [comment]
Forked the project and added:
featureName
location
country
countryCode

to the forward geocoding response. If you think it is useful, please consider merging it to your project.
https://github.com/tijuhasz/cordova-plugin-nativegeocoder/
Thank you for the plugin.

**Comment by sebastianbaar** [comment]
Hey @tijuhasz,

thanks for your feature request - it definitely makes sense! But if we go this way, forward and reverse geocoding will actually return the same object. [Address](https://developer.android.com/reference/android/location/Address) for Android and [CLPlacemark](https://developer.apple.com/documentation/corelocation/clplacemark) for iOS. Thus, we only need to return the same object for both forward and reverse geocoding. This will change the API, though. But I think that it's a good way to go as the native APIs behave the same way. I will consider and implement this and release a new version as soon as possible.

Cheers!

**Comment by tijuhasz** [comment]
Hey @sebastianbaar,

I forked your project and implemented this feature for both Android and iOS. Feel free to use it if it helps you in any way. It is available at:
https://github.com/tijuhasz/cordova-plugin-nativegeocoder/
I tested and used it for Android only.
