### ISSUE TITLE
difference to geocoder of cordova-plugin-googlemaps

### ISSUE THREAD

**Issue by msio** [sebastianbaar/cordova-plugin-nativegeocoder#4]
Hi,
I'd like to know what is the main difference between this plugin and the geocoder of cordova-plugin-googlemaps [here](https://github.com/mapsplugin/cordova-plugin-googlemaps/wiki/Geocoder)
Thanks 
Best Regards

**Comment by sebastianbaar** [comment]
@msio777 It's a lightweight subset of the googlemaps plugin. You have the same functionality in the googlemaps plugin, **but if you only need geocoding** without all the extra google maps stuff and without API keys then this plugin is a lightweight alternative.

**Comment by Hamza-Rahman** [comment]
in my project The District and House name is not work  please give some update 
note: i have  also try the latest one but no luck... it show undefined.. please someone help
![screenshot_2017-04-21-23-55-28](https://cloud.githubusercontent.com/assets/12672574/25290129/61c9bfa8-26ee-11e7-90aa-f408c45db1a2.png)
