### ISSUE TITLE
I'm trying to import NativeGeocoder in the app.module of my project. But I get this error

### ISSUE THREAD

**Issue by CarlosEstevez13** [sebastianbaar/cordova-plugin-nativegeocoder#41]
Type 'NativeGeocorderOriginal' is not assignable to type 'Provider'
Type 'NativeGeocoderOriginal' is missing the following properties from type ''FactoryProvider: provide, useFactory

This is my code
`import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { SplashScreen } from '@ionic-native/splash-screen';
import { StatusBar } from '@ionic-native/status-bar';

import { MyApp } from './app.component';
import { HomePage } from '../pages/home/home';

import { NativeGeocoder } from '@ionic-native/native-geocoder';

@NgModule({
  declarations: [
    MyApp,
    HomePage
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage
  ],
  providers: [
    NativeGeocoder,
    StatusBar,
    SplashScreen,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]
})
export class AppModule {}`

I would really appreciated, if you guys could help me.

**Comment by sebastianbaar** [comment]
Hey @CarlosEstevez13 ,

in Ionic 4 you have to change your import from:
`import { NativeGeocoder } from '@ionic-native/native-geocoder';`
to:
`import { NativeGeocoder } from '@ionic-native/native-geocoder/ngx';
`

Cheers
