### ISSUE TITLE
IOS runtime error - CLGeocoder:geocodeAddressString Error

### ISSUE THREAD

**Issue by bayanAbuawad** [sebastianbaar/cordova-plugin-nativegeocoder#42]
The plugin is working very well on Android, but I am having a weird problem on IOS and it is a runtime problem and not a build problem, I am getting an error on Xcode console saying: 

CLGeocoder:geocodeAddressString Error

And it is not working

**Plugin Version**
v3.1.0

**Smartphone:**
Tested on iPhone 6

**Comment by sebastianbaar** [comment]
Hey @bayanAbuawad,

please update the plugin to v3.1.3 and try again.

Cheers

**Comment by ashishtyd** [comment]
I also have the same issue. For some addresses it shows error CLGeocoder:geocodeAddressString Error
Please help me to resolve this issue.
Ionic Info -
Ionic:

   ionic (Ionic CLI)  : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0, browser 5.0.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.1.4, (and 11 other plugins)

System:

   ios-deploy : 1.9.4
   NodeJS     : v10.15.3 (/usr/local/bin/node)
   npm        : 6.9.0
   OS         : macOS High Sierra
   Xcode      : Xcode 10.1 Build version 10B61

![Screen Shot 2019-03-25 at 3 08 16 PM](https://user-images.githubusercontent.com/32833748/54909655-b8340a00-4f10-11e9-90a0-e960c764e0d6.png)

**Comment by GroupeBEL** [comment]
Hello @sebastianbaar ,
We still having this problem on iOS (Android works fine).
Some addresses are working fine and some other are showing this problem.

Maybe this problem is due to the name of address which contains special characters ..

**Comment by ashishtyd** [comment]
How can I resolve this problem. As you said address string contains special characters(in my case their is only ',' in address) then by removing this it will solve my problem or any thing else need to do.
My app is already in production so please help me to deal with this issue.
Thanks in advance.

**Comment by GroupeBEL** [comment]
@ashishtyd we were having a problem with the database ,  we added the support of utf8 and now when I get the address , I passed within my code and everything is working fine. 

```javascript
let destination = coordinates[0].latitude + ',' + coordinates[0].longitude;
if (this.platform.is('ios')) {
          window.open('maps://?q=' + destination, '_system');
        } else {
          let label = encodeURI('Maps');
          window.open('geo:0,0?q=' + destination + '(' + label + ')', '_system');
        }
```

**Comment by barbarj** [comment]
I'm also having this issue. Oddly enough, it's only happening on iPhones 6, 6S, and 6S+. iOS version doesn't seem to matter. I've tested both 11 and 12. iPhone 7 and up do not experience this issue.

**Comment by QuentinIcky** [comment]
With ios simulator, I have the same error with Iphone XR, X...

**Comment by sebastianbaar** [comment]
Please update to the latest version 3.3.0 and try again. If the error remains, please file a new issue or reopen.

Cheers
