### ISSUE TITLE
Failed to fetch plugin cordova-plugin-nativegeocoder via registry

### ISSUE THREAD

**Issue by Billmike** [sebastianbaar/cordova-plugin-nativegeocoder#43]
When I run the command `ionic cordova plugin add cordova-plugin-nativegeocoder`, I get the following error:
```
Failed to fetch plugin cordova-plugin-nativegeocoder via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! Cannot read property 'match' of undefined
```

ionic-angular: v3.6.1

**Comment by sebastianbaar** [comment]
Hey @Billmike,

try to run the command with a specified version number
`ionic cordova plugin add [PLUGIN_ID]@[VERSION]`

For example:
`ionic cordova plugin add cordova-plugin-nativegeocoder@3.1.3`

Cheers

**Comment by Billmike** [comment]
Hey @sebastianbaar I ran that command, but I'm still getting the same error

```
Failed to fetch plugin cordova-plugin-nativegeocoder@3.2.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! Cannot read property 'match' of undefined
```

**Comment by sebastianbaar** [comment]
Are you able to download any other plugin? I tried in different networks and got no error. It's neither a problem with npm nor with the plugin.

**Comment by Billmike** [comment]
Yeah, I'm able to download other plugins. I downloaded the `cordova-plugin-geolocation` just before. I can also install the `@ionic-native/native-geocoder` library from npm as well.

**Comment by Billmike** [comment]
So it works when I delete my `package-lock.json` file. Closing this now. Thanks for your time @sebastianbaar
