### ISSUE TITLE
native-geocoder not found

### ISSUE THREAD

**Issue by Gajendrasinh** [sebastianbaar/cordova-plugin-nativegeocoder#49]
![image](https://user-images.githubusercontent.com/10431380/63583021-bf993580-c5cc-11e9-906b-689e021ceca1.png)

I am getting above error, how can i fixed this

    "@ionic-native/native-geocoder": "^5.12.0",

**Comment by williamhilldevs** [comment]
simulator or real device?

**Comment by gabriele-sacchi** [comment]
Simulator or real device?

**Comment by sebastianbaar** [comment]
Please update to the latest version 3.3.0 and try again. If the error remains, please file a new issue or reopen.

Cheers
