### ISSUE TITLE
District and House Number show Undefined..

### ISSUE THREAD

**Issue by Hamza-Rahman** [sebastianbaar/cordova-plugin-nativegeocoder#5]
I have face a new problem that District and House number is shown Undefined.. please someone help me 
also i have tried new release on my project  
thank you
![screenshot_2017-04-21-23-55-28](https://cloud.githubusercontent.com/assets/12672574/25290233/fc69402e-26ee-11e7-8359-c5759544cfde.png)

**Comment by 5uper** [comment]
@Hamza-Rhaman
did you update to the latest ionic-native v.3.5.0 ?
https://github.com/driftyco/ionic-native/releases/tag/v3.5.0

**Comment by sebastianbaar** [comment]
@Hamza-Rhaman Can you please share some more info:
- On which device are you running the app? (model, Android or iOS)
- Please share the exact latitude & longitude that you pass to the reverseGeocode()-function

**Comment by Hamza-Rahman** [comment]
i am using android lollipop on samsung sm-p605 tab devise
and do you want to see the code? @sebastianbaar 
i find the house number but not the district .

**Comment by sebastianbaar** [comment]
Maybe the district just isn't defined for the lat&lon you are looking for? Please provide the latitude & longitude so I can have a look if it's a problem with the code or the district just isn't available...
