### ISSUE TITLE
reverseGeocode Error: grpc failed

### ISSUE THREAD

**Issue by chen-nee** [sebastianbaar/cordova-plugin-nativegeocoder#50]
I am getting "Geocoder:getFromLocationName Error: grpc failed" while using reverseGeocode. 

It works after i switch on flight mode and wait for 10 seconds before switching it off again. 

Any idea? Is there any fix or workaround for this?

**Comment by sebastianbaar** [comment]
Please look at the "Known Issues". It's a problem with Google Play Services.

Cheers
