### ISSUE TITLE
Return Address Line or formatted address

### ISSUE THREAD

**Issue by techelogydev** [sebastianbaar/cordova-plugin-nativegeocoder#51]
**Is your feature request related to a problem? Please describe.**
A simple but kind of required feature is to return, along with current Address class values, the value of addressLine which in web API is similar to formatted_address, as creating the address string is sometimes both overhead and improper.

**Describe the solution you'd like**
Just start returning the addressLine in the current response.

**Describe alternatives you've considered**
We now have to construct own address which is not as good and helpful for users. The "unnamed road" and other such keywords irritates users.

**Comment by chaoticvibe** [comment]
It was solved?

**Comment by sebastianbaar** [comment]
Please update to [v3.5.0](https://github.com/sebastianbaar/cordova-plugin-nativegeocoder/releases/tag/v3.5.0)
