### ISSUE TITLE
Not allowed to start service Intent

### ISSUE THREAD

**Issue by kodeine** [sebastianbaar/cordova-plugin-nativegeocoder#56]
if the app is in background it will give that error.

cordova.plugin.nativegeocoder.GeocodingIntentService (has extras) }: app is in background uid UidRecord{9ccb666 u0a555 TPSL idle change:cached procs:1 proclist:1823, seq(0,0,0)}

**Comment by sebastianbaar** [comment]
Please update to latest version 3.4.0
