### ISSUE TITLE
Ionic 3 Native Geocoder return undefined

### ISSUE THREAD

**Issue by surendra-17** [sebastianbaar/cordova-plugin-nativegeocoder#58]
TypeError: Cannot read property 'reverseGeocode' of undefined

import { NativeGeocoder, NativeGeocoderReverseResult, NativeGeocoderForwardResult, NativeGeocoderOptions } from '@ionic-native/native-geocoder';

constructor(private _nativeGeocoder: NativeGeocoder)

main code
this._nativeGeocoder.reverseGeocode(location.lat,location.long, options).then((result: NativeGeocoderReverseResult[]) => {
          console.log(JSON.stringify(result[0]));
          resolve(result[0]);
        }).catch(err => {
            reject(err);
          });

    "@ionic-native/geolocation": "^4.20.0",
    "@ionic-native/native-geocoder": "^4.20.0",
    "cordova-plugin-geolocation": "^4.0.2",
    "cordova-plugin-nativegeocoder": "^3.4.1",

**Comment by Oraicon** [comment]
any update ?

**Comment by sebastianbaar** [comment]
Please use [awesome-cordova-plugins](https://danielsogl.gitbook.io/awesome-cordova-plugins/) and/or update to [v3.5.0](https://github.com/sebastianbaar/cordova-plugin-nativegeocoder/releases/tag/v3.5.0)
