### ISSUE TITLE
huge ios app size increase after install this plugin

### ISSUE THREAD

**Issue by monurakkaya** [sebastianbaar/cordova-plugin-nativegeocoder#59]
**Describe the bug**
Hi,
IOS build and ipa size increses 24.4M to 83.3M with this plugin
Is this normal? 

Apk build size like 10.1M  seems normal.

**To Reproduce**
- cordova plugin add cordova-plugin-nativegeocoder
- ionic cordova build ios --prod --release 

**Plugin Version**
v3.4.1

**Smartphone (please complete the following information):**
 - Device: [Iphone6s]
 - OS: [iOS13.4]

**Additional context**
"dependencies": {
    "@angular/animations": "^9.1.9",
    "@angular/common": "~9.1.6",
    "@angular/core": "~9.1.6",
    "@angular/forms": "~9.1.6",
    "@angular/platform-browser": "~9.1.6",
    "@angular/platform-browser-dynamic": "~9.1.6",
    "@angular/router": "~9.1.6",
    "@ionic-native/core": "^5.0.7",
    "@ionic-native/geolocation": "^5.30.0",
    "@ionic-native/in-app-browser": "^5.27.0",
    "@ionic-native/native-geocoder": "^5.30.0",
    "@ionic-native/onesignal": "^5.26.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.0.0",
    "@ionic/storage": "^2.2.0",
    "@stripe/stripe-js": "^1.5.0",
    "cordova-config": "^0.7.0",
    "cordova-plugin-inappbrowser": "^4.0.0",
    "cordova-sqlite-storage": "^5.0.0",
    "gulp": "^4.0.2",
    "intl-tel-input": "^17.0.0",
    "ngx-paypal": "^6.1.0",
    "onesignal-cordova-plugin": "^2.10.1",
    "rxjs": "~6.5.1",
    "sweetalert2": "^9.13.1",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.5",
    "@angular/cli": "~9.1.5",
    "@angular/compiler": "~9.1.6",
    "@angular/compiler-cli": "~9.1.6",
    "@angular/language-service": "~9.1.6",
    "@ionic/angular-toolkit": "^2.1.1",
    "@ionic/lab": "3.1.6",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "cordova-ios": "^6.1.1",
    "cordova-plugin-add-swift-support": "^2.0.2",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-geolocation": "^4.1.0",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.2.1",
    "cordova-plugin-nativegeocoder": "^3.4.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-sqlite-storage": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-ionic-keyboard": {},
      "onesignal-cordova-plugin": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-geolocation": {
        "GPS_REQUIRED": "true"
      },
      "cordova-plugin-nativegeocoder": {
        "LOCATION_WHEN_IN_USE_DESCRIPTION": "Use geocoder service"
      }
    },
    "platforms": [
      "ios"
    ]
  }

**Comment by gazzaf** [comment]
Did you try cordova platform rm ios
Then cordova platform add ios
Sometimes doing that helps when things go wrong, especially if plugins misbehave. When you remove and add back a platform it also removes and adds back the plugins.
