### ISSUE TITLE
reverseGeocode not working in real device

### ISSUE THREAD

**Issue by janakiram-code** [sebastianbaar/cordova-plugin-nativegeocoder#60]
Hi, 
i'm new to ionic5, I'm working on NativeGeocoder to get address using lat and lag when am using reverseGeocode its not giving the address executing catch block with {} error giving, please find my code 

 getCurrentCoordinates() {
    this.geolocation.getCurrentPosition(this.options).then((resp) => {
      this.latitude = resp.coords.latitude;
      this.longitude = resp.coords.longitude;
      this.getAddress(this.latitude, this.longitude);
      this.getAddress1();
     }).catch((error) => {
       console.log('Error getting location', error);
     });
  }

 getAddress(lat,long){
    this.nativeGeocoder.reverseGeocode(lat,long, this.nativeGeocoderOptions)
    .then((res: NativeGeocoderResult[]) => {
      this.address = this.pretifyAddress(res[0]);
    })
    .catch((error: any) => {
      alert('Error getting location'+ JSON.stringify(error));
    });
  }
![Capturepackage](https://user-images.githubusercontent.com/54915560/112569125-9b858200-8e09-11eb-9371-c7c1524fd31e.JPG)

**Comment by pinkiwagh** [comment]
any one has resolved this issue ??? please informed?? This issue on live project.

**Comment by sebastianbaar** [comment]
Please update to [v3.5.0](https://github.com/sebastianbaar/cordova-plugin-nativegeocoder/releases/tag/v3.5.0)
