### ISSUE TITLE
Sometimes only a partial postcode is returned (iOS)

### ISSUE THREAD

**Issue by gazzaf** [sebastianbaar/cordova-plugin-nativegeocoder#61]
Hi. I don't know if this is an issue with Apple's geocoder or the plugin? Some users are reporting that only the outcode part of the postcode is showing - the first part before the space, either 3 or 4 chars. I've tested this out using location changing in Xcode and I can repeat the issue.
Is there a reason for that and is there a way around it to get a full postcode every time? Thanks.

Gary.

**Comment by sebastianbaar** [comment]
Please update to [v3.5.0](https://github.com/sebastianbaar/cordova-plugin-nativegeocoder/releases/tag/v3.5.0) . If the issue persists, please file an issue with more info, examples and sample code.
