### ISSUE TITLE
Geocoding Pligin Not Fully Functional

### ISSUE THREAD

**Issue by LuckyMasango** [sebastianbaar/cordova-plugin-nativegeocoder#63]
The Geocoding Plugin all of a sudden stopped working, when it does by any chance it only gives three results countryName, administrativeArea and subAdministrativeArea only.

**Comment by sebastianbaar** [comment]
Please update to [v3.5.0](https://github.com/sebastianbaar/cordova-plugin-nativegeocoder/releases/tag/v3.5.0)
