### ISSUE TITLE
Native geocoder result looks different for andriod and ios when do reverse geocode

### ISSUE THREAD

**Issue by siranjeevimurugesan** [sebastianbaar/cordova-plugin-nativegeocoder#65]
When do reverse geocode getting different response from native geocoder result between android and ios. 

For android able to get thoroughfare and subthoroughfare response. But for ios not able to get the response for the same location coordinates. 

**Example:** 
**latitude: 26.640628
locality: "Fort Myers"
longitude: -81.8723084**

**Comment by tamilselvanmariappan** [comment]
**Any solution for this issue?**

When search for a location details with reverse geocode the return value is different for IOS and Android. Noted on the response the lat, lon is changed than what we passed for android but ios it's not changed in response.

We get the postal code, thoroughfare and subthoroughfare as empty

Example input:
Location Name: Grand Canyon
Latitude: 36.09976309999999
Longitude: -112.1124846

Android result
![MicrosoftTeams-image](https://user-images.githubusercontent.com/6248252/199169265-c9ce50e5-9c63-4234-84a8-a6fdc14c7c3a.png)

IOS result
administrativeArea: "AZ"
areasOfInterest: ["Grand Canyon National Park"] (1)
countryCode: "US"
countryName: "United States"
latitude: "36.09976309999999"
locality: "Williams"
longitude: "-112.1124846"
postalCode: ""
subAdministrativeArea: "Coconino County"
subLocality: ""
subThoroughfare: ""
thoroughfare: ""

**Comment by jhanzaibkhadim199** [comment]
Any solution for this issue ?? or any workaround ?

**Comment by sebastianbaar** [comment]
This plugin only uses iOS [CoreLocation](https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CoreLocation_Framework/) service and Android [Geocoder](https://developer.android.com/reference/android/location/Geocoder.html) class. It does not alter/change the responses of these native frameworks. I can reproduce you issue but I cannot fix the native framework's responses.
