### ISSUE TITLE
reverseGeocode return "ebhg: UNAVAILABLE: Unable to resolve host geomobileservices-pa.googleapis.com"

### ISSUE THREAD

**Issue by EYALIN** [sebastianbaar/cordova-plugin-nativegeocoder#66]
it's not happen always. what can be the reason for that?

Ionic: 6.2
"cordova-plugin-nativegeocoder": "^3.4.1"
cordova-Android: 11

**Comment by sebastianbaar** [comment]
Do you have this error on a device or on an emulator? Which device, Android version, ...

Please check [Known Issues](https://github.com/sebastianbaar/cordova-plugin-nativegeocoder#android) first.
