### ISSUE TITLE
IOS build failing with NSObject can be declared @objc error 

### ISSUE THREAD

**Issue by ChaitGSZyx** [sebastianbaar/cordova-plugin-nativegeocoder#68]
**Describe the bug**
we are running ionic cordova v6
Error:
Plugins/cordova-plugin-nativegeocoder/NativeGeocoder.swift:28:2 Only classes that inherit from NSObject can be declared @objc
<img width="972" alt="Screenshot 2023-06-08 at 11 18 46 AM" src="https://github.com/sebastianbaar/cordova-plugin-nativegeocoder/assets/134209081/4826f264-a55e-44d8-81fa-bdcf65c1db6a">

My xcode version is 14.3.1
**To Reproduce**
tried cleaning & rebuilding , remove & reinstalling pods and checking swift versions nothing worked

**Expected behavior**
Build should be successful and 

**Plugin Version**
   "cordova-plugin-nativegeocoder": "^3.4.1",
tried with 3.5.1 as well still same issue

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] or Emulator: [e.g. Nexus 7]

**Additional context**
<img width="551" alt="Screenshot 2023-06-08 at 11 30 54 AM" src="https://github.com/sebastianbaar/cordova-plugin-nativegeocoder/assets/134209081/39a9e167-d9c9-46da-a252-3839729adb91">

This above error occurs when I do ionic cordova build ios from terminal.
all the hidden boxes says my project name

**Comment by ChaitGSZyx** [comment]
@sebastianbaar could you please help us with the issue

**Comment by sebastianbaar** [comment]
Hey @ChaitGSZyx, I am not able to reproduce your issue. It seems like you have a problem with importing `CDVPlugin`. 

Can you please check if `CDVPlugin` is available (Xcode > CordovaLib > Public > CDVPlugin).

Do you use other cordova libs in your app and are you able to build your app without the nativegeocoder lib?

Are you able to reproduce the issue in a minimal example project?
