### ISSUE TITLE
Plugin needs to be updated to Swift 3

### ISSUE THREAD

**Issue by ihadeed** [sebastianbaar/cordova-plugin-nativegeocoder#7]
XCode 8 can no longer compile apps that use an older version of Swift. The automatic converting feature of XCode seem to work fine, the build did not throw any errors afterwards. But I haven't tested the plugin yet.

**Comment by sebastianbaar** [comment]
@ihadeed Thanks for pointing this out. I will soon have a look at it and port it to Swift 3.

**Comment by piyushmanurkar** [comment]
Any update about this. I am using xCode Version 8.3.2...
