### ISSUE TITLE
forward geocoding returns different lat long based on devices. 

### ISSUE THREAD

**Issue by vt-ombalakumar** [sebastianbaar/cordova-plugin-nativegeocoder#8]
Hi , i was working in geocoding and getting lat long for an address or zipcode which is being entered by the user, when i was testing with 10004 zipcode, which is near newyork, we are getting different lat long for different devices example : samsung galaxy s7 returns lat : 40.705478 long :  -74.015044 where as in lenovo k4 note returns lat : 48.586179 long : 4.107207 . I don't know why it is returning different lat long for same zipcode . Can you please help me on this.

**Comment by sebastianbaar** [comment]
Hey @vt-ombalakumar I tried with different devices with the search term "10004 New York". I can only observe small deviations in the lat and long across multiple devices and OSs (Android and iOS). Unfortunately, I cannot reproduce your bug. Does this error occur multiple times on the same device? Do the Android versions differ?

**Comment by vt-ombalakumar** [comment]
hi @sebastianbaar , thanks for the reply If you can, please try with only zipcode , (i.e) "10004"  with different android versions and check , thanks

**Comment by sebastianbaar** [comment]
I only have one Android device at the moment. On iOS using only a zip code does not work (you get an error because of insufficient information). Thus, I cannot really test it, sorry. Maybe you can give it a try with other devices and let me know what you've found out. Cheers

**Comment by vt-ombalakumar** [comment]
hi, thanks..
