### ISSUE TITLE
Error when finding position

### ISSUE THREAD

**Issue by ThorvaldAagaard** [sebastianbaar/cordova-plugin-nativegeocoder#9]
During my approval of an App for the AppStore I hit a bug, that puzzles me a lot.

The Apple headquarter is located at: Apple Infinite Loop, 1 Infinite Loop, Cupertino, Californien, USA

On Android I get the location 37.3316756, -122.030189 but on iPhone I get the error message: "Cannot get a location"

If I search for: "Apple, Infinite Loop, Cupertino, Californien, USA"  or "Apple, 1 Infinite Loop, Cupertino, Californien, USA" it works fine on both platforms.

I am using Google Places to find the address, when the user enters the address.

Using maps.google.com the address results in this:
![image](https://user-images.githubusercontent.com/10560652/28321265-1c3bfcba-6bd3-11e7-8cdd-a51f02d927b8.png)

**Comment by sebastianbaar** [comment]
Hey @ThorvaldAagaard unfortunately I get the same Error. When debugging I get the Error Code 8 (https://developer.apple.com/documentation/corelocation/clerror.code/1423587-geocodefoundnoresult) which simply means that the "geocode request yielded no result". That's a problem with the CLGeocoder thus there is no solution only to try to somehow convert the search string to a valid (and searchable) format. Hope you find a solution for this! Cheers

**Comment by ThorvaldAagaard** [comment]
I solved the actual problem by restricting the search to be addresses
